server:
    port: 8080
    servlet:
        context-path: /identity


spring:
    datasource:
        url: "jdbc:mysql://localhost:3306/identity_service"
        driverClassName: "com.mysql.cj.jdbc.Driver"
        username: root
        password: root


    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true

jwt:
    signerKey: "Ot9t5aGxoRKLti29eTn9MhuIcBitnGrs7w7N0+CXpk7BUHbK/ZVA97p17967gPG3"
    valid-duration: 3600 # in second -> token will expire after 3600 seconds
    refreshable-duration: 360000 # in second -> token will be able to be refreshed in 360000 seconds
                                 # # even when the token is expired, it still can be refreshable in an amount of time