server:
  port: 8080
  servlet:
    context-path: /identity

spring:
  datasource:
    url: ${DBMS_CONNECTION:jdbc:mysql://localhost:3306/identity_service}
    driverClassName: "com.mysql.cj.jdbc.Driver"
    password: ${DBMS_PASSWORD:root}
    username: ${DBMS_USERNAME:root}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  application:
    name: deliver-tracking
  mvc:
    view:
      prefix: /templates/
      suffix: .html

jwt:
  signerKey: "1TjXchw5FloESb63Kc+DFhTARvpWL4jUGCwfGWxuG5SIf/1y/LgJxHnMqaF6A/ij"
  valid-duration: 3600 # in second
  refreshable-duration: 36000 # in seconds


graphhopper:
  api:
    key: 3cde815c-380c-4820-b820-1e6ce3017080